import type { AchievementDefinition } from '@/types/achievements';

export const GLOBAL_ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'global.first_launch',
    scope: 'global',
    title: 'Подключение установлено',
    description: 'Запустить любую игру на портале впервые.',
    icon: '🛰️',
    hidden: false,
    type: 'boolean',
    points: 5,
  },
  {
    id: 'global.both_games',
    scope: 'global',
    title: 'Двойной агент',
    description: 'Поиграть в обе игры портала.',
    icon: '🎭',
    hidden: false,
    type: 'counter',
    target: 2,
    points: 15,
  },
];

export const COLONY_ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'colony.first_building',
    scope: 'colony',
    title: 'Первый камень',
    description: 'Построить первое здание в колонии.',
    icon: '🏗️',
    hidden: false,
    type: 'boolean',
    points: 10,
  },
  {
    id: 'colony.survive_10_days',
    scope: 'colony',
    title: 'Закалённые',
    description: 'Пережить 10 дней.',
    icon: '📅',
    hidden: false,
    type: 'counter',
    target: 10,
    points: 20,
  },
  {
    id: 'colony.population_20',
    scope: 'colony',
    title: 'Растущий улей',
    description: 'Достичь населения в 20 жителей.',
    icon: '👥',
    hidden: false,
    type: 'counter',
    target: 20,
    points: 25,
  },
  {
    id: 'colony.first_tech',
    scope: 'colony',
    title: 'Искра прогресса',
    description: 'Открыть первую технологию.',
    icon: '🔬',
    hidden: false,
    type: 'boolean',
    points: 15,
  },
  {
    id: 'colony.repel_raid',
    scope: 'colony',
    title: 'Отбили атаку',
    description: 'Успешно отразить налёт на колонию.',
    icon: '🛡️',
    hidden: false,
    type: 'boolean',
    points: 20,
  },
  {
    id: 'colony.all_tech',
    scope: 'colony',
    title: 'Эпоха науки',
    description: 'Открыть все технологии.',
    icon: '🧪',
    hidden: false,
    type: 'boolean',
    points: 25,
  },
];

export const SHADOW_ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'shadow.first_case',
    scope: 'shadow',
    title: 'Дело закрыто',
    description: 'Завершить первое расследование.',
    icon: '🗂️',
    hidden: false,
    type: 'boolean',
    points: 10,
  },
  {
    id: 'shadow.all_evidence',
    scope: 'shadow',
    title: 'Дотошность',
    description: 'Изучить все улики в одном деле.',
    icon: '🔍',
    hidden: false,
    type: 'boolean',
    points: 15,
  },
  {
    id: 'shadow.flawless',
    scope: 'shadow',
    title: 'Без единой ошибки',
    description: 'Пройти дело, ответив на все вопросы верно.',
    icon: '✅',
    hidden: false,
    type: 'boolean',
    points: 25,
  },
  {
    id: 'shadow.perfect_rank',
    scope: 'shadow',
    title: 'Идеальный детектив',
    description: 'Получить рейтинг S за расследование.',
    icon: '🏆',
    hidden: true,
    type: 'boolean',
    points: 30,
  },
  {
    id: 'shadow.two_cases',
    scope: 'shadow',
    title: 'Серийный следователь',
    description: 'Раскрыть два разных дела.',
    icon: '🗃️',
    hidden: false,
    type: 'boolean',
    points: 20,
  },
];

export const ALL_ACHIEVEMENTS: AchievementDefinition[] = [
  ...GLOBAL_ACHIEVEMENTS,
  ...COLONY_ACHIEVEMENTS,
  ...SHADOW_ACHIEVEMENTS,
];
